# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
GITHUB_COMMENT_REPORTER: false
DISABLE_LINTERS:
  # We are setting KUBERNETES_DIRECTORY to the helm chart so the
  # KUBERNETES_HELM linter can find the chart, but then this linter expects to
  # find raw Kubernetes manifests in this directory, which isn't the case.
  # If we added a PRE_ command with a `helm template` step, and further
  # restricted the included files for this linter, it *might* work.
  - KUBERNETES_KUBECONFORM
  # TBD how to use this from Megalinter with our setup.
  - KUBERNETES_KUBESCAPE
  # Repository-wide link checking returns mostly false positives (like internal
  # service URLs in templates).
  - SPELL_LYCHEE
  # yamllint is sufficient for us.
  - YAML_PRETTIER
DISABLE_ERRORS_LINTERS:
  # Include grammar checks only as warnings.
  - SPELL_PROSELINT
  - SPELL_VALE
  # This may be informative but doesn't need to break the build.
  - COPYPASTE_JSCPD
  # TBD! Need to work through these.
  - REPOSITORY_TRIVY
  - REPOSITORY_CHECKOV
SPELL_CSPELL_ANALYZE_FILE_NAMES: false
# Make sure Vale is setup to run with the styles it needs.
SPELL_VALE_PRE_COMMANDS:
  - command: mkdir -p styles
    cwd: "workspace"
  - command: vale sync
    cwd: "workspace"
# Ignore YAML files with templating macros; these typically fail linting and/or
# schema checking.
FILTER_REGEX_EXCLUDE: '(templates/.*\.yml|templates/.*\.yaml)'
KUBERNETES_DIRECTORY: charts/lfx-platform
KUBERNETES_HELM_ARGUMENTS: charts/lfx-platform
KUBERNETES_HELM_PRE_COMMANDS: |
  helm dependency update charts/lfx-platform
